config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  get 'hello_world', to: 'hello_world#index'

  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for controllers: { sessions: 'users/sessions' }

  authenticated :user, ->(u) { u.admin? } do
    namespace :admin do
      resources :announcements
      resources :users
      require 'sidekiq/web'
      mount Sidekiq::Web => '/sidekiq'

      root to: 'users#index'
    end
  end

  authenticated :user do
    resources :announcements, only: %i[index show]

    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    get 'home/index'

    root to: 'home#index', as: :user_root
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
end

app/views/layouts/_dropdown.html.erb
    <% if user_signed_in? %>
  <div class="btn-group">
    <%= link_to "What's New", announcements_path,
                method: :get,
                class: "text-dark" %>
  </div>
<% end %>
<div class="btn-group mr-3">
  <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Account
  </button>
  <div class="dropdown-menu dropdown-menu-left">
    <!-- Dropdown menu links -->
    <% if user_signed_in? %>
      <%= link_to "Account", edit_user_registration_url, class: "dropdown-item" %>
      <%= link_to "Sign Out",  destroy_user_session_path(), 
                class: "dropdown-item" %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path,
                method: :get,
                class: "dropdown-item" %>
    <% end %>
    <% if user_signed_in? && current_user.admin? %>
      <div class="dropdown-divider"></div>
      <%= link_to "Admin", admin_root_path,
                method: :get,
                class: "dropdown-item" %>
      <%= link_to "Sidekiq",  admin_sidekiq_web_path,
                method: :get,
                class: "dropdown-item" %>
      <%= link_to "Letter Opener", letter_opener_web_path,
                method: :get,
                class: "dropdown-item" %>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light align-middle">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Link1 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link2</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link3</a>
      </li>
    </ul>
  </div>
  <%= render 'layouts/dropdown', class: 'mr-5'%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Template</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/nav'%>
    <% if notice %>
      <div class="alert alert-primary alert-dismissible fade show">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <p class="alert text-danger text-center"><%= alert %></p>
    <div class="container text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>